import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modal: {
    alignSelf: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,

    top: '25%',
    width: '80%',
    paddingTop: 30,
    borderRadius: 16,
    backgroundColor: '#FAFAFA',
    shadowColor: '#000',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowRadius: 5,
    shadowOpacity: 0.5,
  },
  mapWrapper: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  mapView: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  findUserButton: {
    marginBottom: 15,
    marginRight: 15,
    width: 45,
    height: 45,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    elevation: 10,
    zIndex: 100,
  },
  findButton: {
    marginBottom: 15,
    marginRight: 15,
    width: 45,
    height: 45,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    elevation: 10,
    zIndex: 100,
  },
  mapsButton: {
    marginBottom: 15,
    marginRight: 15,
    width: 45,
    height: 45,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    elevation: 10,
    zIndex: 100,
  },
  informationWrapper: {
    paddingRight: 40,
    paddingBottom: 10,
    paddingTop: 15,
    paddingLeft: 30,
    backgroundColor: '#FFF',
    alignItems: 'flex-start',
    borderTopLeftRadius: 40,
    elevation: 5,
  },
});
